### ISSUE TITLE
Use Haiku's ColumnListView and get rid of SGB

### ISSUE THREAD

**Issue by diversys** [HaikuArchives/BePodder#11]
Maybe @aarroyoc is interested as he did the same for BePDF.

**Comment by janus2** [comment]
Hi diversys, do you keep open this issue for the splitview? They are ugly but very useful :-)

**Comment by diversys** [comment]
No, I though that mentioning "fixes" in the commit message would have closed it automatically but it  didn't. See https://help.github.com/articles/closing-issues-using-keywords/
