### ISSUE TITLE
Make Haiku MediaPlayer default

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/BePodder#25]
When launching BePodder for the first time, I was presented with a notification that VLC was required, and given an option to download. I found that confusing. It wasn't until I went through the preferences that I discovered that MP was listed as an option. It should be the default.

**Comment by janus2** [comment]
This is because the default is **auto** this is an awesome feature, but because BePodder is old need to be updated. For each format there is associated the best player for that format, probably in this moment in time for all the format is MP. But it's a cool feature for the future.

**Comment by Vidrep** [comment]
Haiku MP in its current state (particularly on 64 bit, using ffmpeg 3) is entirely capable of handling any format, plus it is now able to stream the content, instead of downloading MB of files.
