### ISSUE TITLE
Make WebPositive default browser

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/BePodder#26]
NetPositive and Firefox are listed as browser options in the preferences. The default needs to be changed to WebPositive. Other optional browsers available on current Haiku should be listed as options I.e. Qupzilla, etc.

**Comment by diversys** [comment]
It could query mimedb for supported apps.

**Comment by janus2** [comment]
@Vidrep are you using an old version?  I changed the browser a lot of commit ago...

@diversys  I already tried that approach but there are a lot of apps that match the mime-type but are not very useful... even using only the sub type. (maybe I have too many apps installed on my system... There is  a ticket open for this by j. stressman IIRC)

**Comment by Vidrep** [comment]
I just installed BePodder for the first time yesterday (on x86_64). My impression was "this must be a really old app. It lists NetPositive and Firefox as browsers - no WebPositive".

**Comment by janus2** [comment]
from Haikudepot?

**Comment by Vidrep** [comment]
Yes, from HaikuDepot

**Comment by janus2** [comment]
It's a very very old version...

**Comment by janus2** [comment]
I wrote here how to try the new one

`git clone https://github.com/HaikuArchives/BePodder.git`

`cd BePodder`
`(cd library/librunview/ ; make)`
`(cd library/libfunky/ ; make)`
`(cd library/libfish/ ; make)`
`cd sources; make`
in  the object.architecure+release you will found BePodder

The new version is not compatible with  the old you can export the feed from the new and reimport them.

**Comment by Vidrep** [comment]
I built BePodder from source as instructed above and now I see the changes. I'll use this as the basis for bug reports and suggestions from this point forward. We really need to get the current revision into HaikuDepot. Thanks!

**Comment by janus2** [comment]
I'm glad you like it.
