### ISSUE TITLE
Enhancement: Add option for Haiku MP to stream content

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/BePodder#27]
Haiku MP now has the ability to stream podcasts. This could be added as an option. I have tested it and it works fine.

**Comment by Vidrep** [comment]
Maybe we could entice or bribe Barrett into getting involved here. :)

**Comment by janus2** [comment]
If I'am not too sleepy you will find a surprise

**Comment by janus2** [comment]
Boom, done!

**Comment by janus2** [comment]
I cannot believe this function exists even in the HaikuDepot version, but is very buggy!
Just press play on an enclosure and it should play in streaming (30% of the time works all the time)

**Comment by janus2** [comment]
I thinks the bug is that sometimes it plays

**Comment by janus2** [comment]
Let me know about this solution I have saved the other one... but this feels much neat

**Comment by Vidrep** [comment]
Just did a git pull and tested the streaming feature - works great! No point using up HDD space for downloads every time you want to view or listen to a podcast.

**Comment by janus2** [comment]
Cool. Cool, cool, cool.
Yes it is a very nice feature, good suggestion!
I think BePodder is starting to be in good shape.

**Comment by Vidrep** [comment]
Agreed. It would also be advantageous to discuss in real time on IRC #haiku-3rdparty
