### ISSUE TITLE
[RFC] Choose a good directory for the BePodder archive

### ISSUE THREAD

**Issue by janus2** [HaikuArchives/BePodder#31]
At the moment BePodder saves the archive in the config/cache this directory should be used only for information that the app can rebuild. Most applications save the data in config settings even if this directory should be used only for settings. Any advice is appreciate...

**Comment by scottmc** [comment]
This might be a good question to ask on the dev mailing list.

**Comment by humdingerb** [comment]
Personally, I think defaulting to /boot/home/BePodder/ and having it user settable would be best.

**Comment by janus2** [comment]
Generally I don't like to pollute the home directory, but the archive has the attributes and they can be seen by  the tracker... I'm not so sure on the fact that it should be settable.

**Comment by Vidrep** [comment]
We should try to have some consistency where the cache is located for apps. BurnItNow, for example, has its default location in /boot/system/cache. However, the end user also has the option of setting the location "Set cache folder...".

**Comment by janus2** [comment]
The problem is that this is not a cache is the archive of BePodder, in theory the system could delete the files if needed.

**Comment by Vidrep** [comment]
In that case, we need to rename it to "BePodder/Archive" and keep it in the /home directory as humdinger suggested.

**Comment by janus2** [comment]
That exactly how it is called now just in the cache directory... Probably I overthinking because the user should put his file in a folder called "Documents" but I am always afraid to pollute the user forlders... I am against the customizable path in the settings because after the user has started to use the program the archive can became big and if he will choose another disk/partition move the archive it will take a lot of time.

**Comment by humdingerb** [comment]
How about asking the user to set the archive folder if it hasn't been set before, i.e. on first launch?

**Comment by janus2** [comment]
I would prefer a zero config experience...

**Comment by scottmc** [comment]
https://www.haiku-os.org/docs/api/FindDirectory_8h.html
B_USER_DATA_DIRECTORY /BePodder ?

**Comment by janus2** [comment]
I have tried some time ago. This return NULL and the error is Read-only file system. Probably is a directory in the package.

**Comment by janus2** [comment]
> https://www.haiku-os.org/docs/api/FindDirectory_8h.html
B_USER_DATA_DIRECTORY /BePodder ?

I have opened a ticket for this, I found that exist a B_USER_NONPACKAGED_DATA_DIRECTORY but I cannot understand why there are two of these... Should be like CACHE and PREFERENCES.

If nothing change all in favor to use B_USER_NONPACKAGED_DATA_DIRECTORY?

**Comment by scottmc** [comment]
works for me

**Comment by KevinAdams05** [comment]
Works for me too
