### ISSUE TITLE
Check release version

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/BePodder#32]
The version listed under releases on GitHub is showing version 1.4.0
https://github.com/HaikuArchives/BePodder/releases

However, when building from source the version number is still shown as:
"Version: Appcaster (ALPHA) 1.3.0

**Comment by scottmc** [comment]
Please make sure that when tagging a release that you give same version in the .rdef files, any about boxes, etc.  Perhaps do a new tagged release soon and bump to 1.4.1 or 1.5 even.  We have open GCI task to have a student test 1.4.0 and report issues.  After that we might open one to have them fix open issues, but holding off for now since janus2 is on a roll.

**Comment by Vidrep** [comment]
I think janus2 has stopped rolling on this app. It appears to be in good shape currently, and I'm looking forward to seeing the recent commits in HaikuDepot. janus2, thoughts, comments?

**Comment by janus2** [comment]
I think we are waiting for the end of the GCI to see if a participant wants to fix some bug. There are tons of improvements we can make and there are a few things I must fix before we build the package. But I am jumping from a project to another just for fun but I always come back to tweak something in applications I have already ruined;-) ... I'm trying to put other apps in good shape but for he big one is very time-consuming.

**Comment by scottmc** [comment]
Yes, GCI ends in a couple weeks.  I think we should then look at many of these and create tagged releases, at least where it make sense to.  Ones that have seen lots of recent updates and are in generally good shape.

**Comment by scottmc** [comment]
Time for a new release yet?  Or were there specific issues that should be fixed first?

**Comment by Vidrep** [comment]
We need to sort out the release version number. The package in HaikuDepot is tagged as v1.4.0-1. However, it is actually still 1.3.0 (still the old version) that is installed by pkgman. How about we release BePodder as it is currently in HaikuArchives and tag as 1.4.0-2, just to end the confusion, and bunp to 1.5.0 when Janus2 has decided he's done with any further updates?
Comments?

**Comment by janus2** [comment]
Before a new release is important that the issue https://dev.haiku-os.org/ticket/14037 is sorted out.

**Comment by scottmc** [comment]
@janus2 Looks like you closed that issue out, so might this one be ready for a new release soon?  Remember to update the version info in all places prior to tagging the release

**Comment by scottmc** [comment]
@janus2 perhaps do a pre-release tag now, and then a full release after Dec 12th.  We have GCI coing up Oct-23-Dec12th, and some of the open issue here might make for good GCI tasks.

**Comment by janus2** [comment]
I think if there is a Haiku beta soon this should be a full release. @Vidrep what do you think?
BePodder works pretty well now.

**Comment by janus2** [comment]
This should be fixed in  4be2c6bdd9906fb7d235c349331a0a0646adeb74 
Version updated to 1.5.0 in resources and in the source code.
