### ISSUE TITLE
Show entire channel image

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/BePodder#35]
Only a very small portion of the channel image is shown in the subscriptions column. 
Is it possible to downsize entire image to fit?
See screenshot: https://imgur.com/a/2AYZM

**Comment by janus2** [comment]
you had two versions of BePodder...
An old one and a new one, you have loaded the podcast with the old one and now you are using the new one... Keep only one version!

**Comment by janus2** [comment]
solution export the feed and import the feed in the new version of bepodder

**Comment by janus2** [comment]
if I am wrong can you post the feed link here a give a quick look

**Comment by Vidrep** [comment]
I deleted the archive and added again. That fixed the problem, as you suggested.
Close the issue
