### ISSUE TITLE
Allow editing feed URL

### ISSUE THREAD

**Issue by sfanxiang** [HaikuArchives/BePodder#37]

**Comment by janus2** [comment]
Why?

**Comment by janus2** [comment]
Why? Almost all the applications dealing with rss doesn't allow this. This create only a lot of tecnical problems.

**Comment by sfanxiang** [comment]
I just made a typo in an URL by mistake, wanted to go back editing, and found I couldn't.

**Comment by janus2** [comment]
You should delete and recreate the feed. A better approach is cut and paste.
The application if in the clipboard there is a url automatically will use the url to populate the field.

**Comment by janus2** [comment]
This cannot be implemented.
