### ISSUE TITLE
Better error reporting

### ISSUE THREAD

**Issue by sfanxiang** [HaikuArchives/BePodder#38]
Currently some error reports are specific, but many more just show "error". It can be helpful to show the socket error description or the result from the webpage instead.

**Comment by janus2** [comment]
Can you specify witch error you encounter without an appropriate description. Thanks

**Comment by sfanxiang** [comment]
After some tests I found that URLs with an HTTP query ("?") result in error.

In the screenshot below, the first subscription does not have a "?", and the second one does. Notice the first shows "not found", which is correct, and the second shows "error". At the bottom both github subscriptions are working because they don't have a "?".

![img_20180112_214540](https://user-images.githubusercontent.com/5893440/34877704-141b96ee-f7e2-11e7-9491-b0408d71cbd9.jpg)

**Comment by janus2** [comment]
I have copied the link that gives "error" to you and works fine on my BePodder
![l2inc](https://user-images.githubusercontent.com/10423645/35148911-69fb3ace-fd14-11e7-8692-bc35954a37fc.png)
For the others links or are unreachable or the https:// works. Strange behavior.

**Comment by janus2** [comment]
![cat](https://user-images.githubusercontent.com/10423645/35149043-eb10c6ce-fd14-11e7-94e5-09b03e0e72e1.png)

**Comment by sfanxiang** [comment]
Oh there's one extra newline at the end of each "error" URL. I thought it was like torrent clients, which accept empty lines in the URL list.

Sorry for the confusion. Maybe we can report "invalid URL" in this case, or simply trim the URL.
