### ISSUE TITLE
Youtube videos won't donloading 

### ISSUE THREAD

**Issue by punsith** [HaikuArchives/BePodder#4]
When I incest a YouTube link 
![screenshot 115](https://cloud.githubusercontent.com/assets/24215220/21406528/2342d6ce-c79a-11e6-8a77-fab1939da59f.png)
the message says "invalid format"

**Comment by janus2** [comment]
punsith you must insert the feed of the youtube channel not a single video:
The url is usually something like this 
https://www.youtube.com/feeds/videos.xml?channel_id=<the channel of you choice>
But with the new policy of youtube you can't download the video you can only receive the notification of new videos. 

This issue can be close as invalid.

**Comment by humdingerb** [comment]
Thanks for checking.
