### ISSUE TITLE
Make date locale aware

### ISSUE THREAD

**Issue by sfanxiang** [HaikuArchives/BePodder#43]
Only MM/DD/YY is supported right now. Would be nice to have other formats like DD/MM/YY.

**Comment by scottmc** [comment]
Try changing your system local to a different location that uses a different date format and see if it changes, if not then change this to "Make date be locale aware".

**Comment by janus2** [comment]
Unfortunately, the BColumnListView dataField is not locale aware this is a Haiku problem.
