### ISSUE TITLE
Crash when checking channel

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/BePodder#50]
hrev51768 x86_gcc2h
Checking a channel while playing an audio stream caused a crash
Debugger report attached
[BePodder-2239-debug-19-01-2018-23-35-24.report.txt](https://github.com/HaikuArchives/BePodder/files/1648291/BePodder-2239-debug-19-01-2018-23-35-24.report.txt)

**Comment by Vidrep** [comment]
I cannot reproduce this issue anymore

**Comment by janus2** [comment]
I close this for know
