### ISSUE TITLE
Quit MediaPlayer at conclusion of streamed content

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/BePodder#54]
When streaming a podcast, it would be nice to have MediaPlayer quit at the conclusion of the stream. Not sure if this is possible.

**Comment by janus2** [comment]
In the Mediaplayer in the menu Settings... "Play mode" under the checkbox "Automatically start playing" there are 2 checkboxes:
- Close window after playing video
- Close window after playing audio
Those settings should do what you are asking, but there is a bug and the audio stops at -0:01.
I think this is a Haiku bug.

**Comment by janus2** [comment]
This should be addressed in the MediaPlayer
