### ISSUE TITLE
Remove registration information from helpR5.xml

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/BePodder#59]
Register your copy
The trial program is fully-functional but is will run only 30 days from the first time you open the application.
Please pay the shareware fee, it's only 15 euro (Kagi add tax in some countries), BePodder licence can be purchased online from Kagi.
(http://www.funkyideasoft.com/buy_bp.html)' Buy at www.funkyideasoft.com 
After purchasing, an email will be sent to you with a keyfile and instruction on how to install it. It's just a matter of unzipping a file and moving it to a certain directory. 
There is no problem updating BePodder when a new version becomes available. The keyfile will unlock all downloadable packages unless otherwise notified.

**Comment by diversys** [comment]
Should be fixed in d581072e7316026d86865f38b80ccb0f2b5f54f6
