### ISSUE TITLE
While donwloading if I press the check buton everything become mess

### ISSUE THREAD

**Issue by punsith** [HaikuArchives/BePodder#6]
The downloading is like "14%" then it gose to "1%" then again "3%" just like random numbers  video is on this link :: 
https://drive.google.com/open?id=0B7xGWjXyxh6HVUhIcEhRd28tYzQ

**Comment by janus2** [comment]
I can't reproduce the problem. Can you post the link of the feed that gives you problem? From the video looks like you are trying to download a video instead of a feed. Am I wrong?
The application should reply invalid format.

**Comment by janus2** [comment]
I close this for now. If happen again please reopen.
