### ISSUE TITLE
BePodder crash after closing help menu

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/BePodder#61]
hrev51834 x86_64
```
KERN: 2187: DEBUGGER: _sizeClass >= 0
KERN: debug_server: Thread 2187 entered the debugger: Debugger call: `_sizeClass >= 0'
KERN: stack trace, current PC 0x1da9be64d59  _kern_debugger + 0x9:
KERN:   (0x7f14ccb74690)  0x1da9be6b450  __assert_fail + 0x43
KERN:   (0x7f14ccb746c0)  0x1da9bf06bfe  _ZN8BPrivate11processHeap4freeEPv + 0xd4
KERN:   (0x7f14ccb74700)  0x1da9bf08615  free + 0xfc
KERN:   (0x7f14ccb74720)  0x77936785d2  _ZN4HDocD0Ev + 0x72
KERN:   (0x7f14ccb74760)  0x7793674c68  _ZN10HelpViewerD2Ev + 0x58
KERN:   (0x7f14ccb74790)  0x7793674db1  _ZN10HelpViewerD0Ev + 0x11
KERN:   (0x7f14ccb747b0)  0x1695777a071  _ZN5BViewD2Ev + 0x57
KERN:   (0x7f14ccb747e0)  0x1695777a17f  _ZN5BViewD0Ev + 0x11
KERN:   (0x7f14ccb74800)  0x16957781378  _ZN7BWindowD1Ev + 0xb0
KERN:   (0x7f14ccb74860)  0x7793644e5f  _ZN10HelpWindowD0Ev + 0x1f
KERN:   (0x7f14ccb74880)  0x169576cab02  _ZN7BLooper4QuitEv + 0xa8
KERN:   (0x7f14ccb748b0)  0x16957782cdd  _ZN7BWindow4QuitEv + 0x95
KERN:   (0x7f14ccb748d0)  0x169576cabf1  _ZN7BLooper14_QuitRequestedEP8BMessage + 0x35
KERN:   (0x7f14ccb74980)  0x169576cacc5  _ZN7BLooper15DispatchMessageEP8BMessageP8BHandler + 0x29
KERN:   (0x7f14ccb74990)  0x16957785a72  _ZN7BWindow15DispatchMessageEP8BMessageP8BHandler + 0x13a4
KERN:   (0x7f14ccb74cb0)  0x1695777f82d  _ZN7BWindow11task_looperEv + 0x267
KERN:   (0x7f14ccb74d50)  0x169576c9a27  _ZN7BLooper7_task0_EPv + 0x21
KERN:   (0x7f14ccb74d70)  0x1da9be63b71  thread_entry + 0x12
KERN: debug_server: Killing team 2150 (/boot/home/HaikuArchives/BePodder/release/BePodder)
KERN: debug_server: TeamDebugHandler::Init(): Failed to get info for team 2150: Operation on invalid team
KERN: debug_server: KillTeam(): Error getting info for team 2150: Operation on invalid team
KERN: debug_server: Killing team 2150 ()
```

**Comment by Vidrep** [comment]
Running BePodder from terminal:

Welcome to the Haiku shell.

~/HaikuArchives/BePodder/release> BePodder
Installing channel MimeType..
Error installing!
Installing item MimeType..
Error installing!
Installing archived channel MimeType..
Error installing!
Thread ready [qSubscriptions's enemy #0] 2355
Thread ready [qSubscriptions's enemy #1] 2356
Thread ready [qSubscriptions's enemy #2] 2357
Thread ready [qEnclosures's enemy #0] 2358
Thread ready [qExtra's enemy #0] 2359
Recaching for.. http://www.BillOReilly.com/podcast?categoryID3=727
Recaching for.. https://audioboom.com/channels/3996073.rss
Recaching for.. https://rss.art19.com/rush-limbaugh-morning-update
Recaching for.. http://www.omnycontent.com/d/playlist/a7b0bd27-d748-4fbe-ab3b-a6fa0049bcf6/0ae30834-cd72-4de8-b4cc-a84100ffe5b9/0707a91d-fe5c-4035-9b70-a84100ffe5c7/podcast.rss
Parsing time 0 secs. 
Number of pages 11
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/help1.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/dot.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/diagram1.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/dot2.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/gui1.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/info_button.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/gui2.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/gui3.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/gui4.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/gui5.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/gui6.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/gui7.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_alt.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_ctrl.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_alt.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_ctrl.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_q.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/arrow.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_alt.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_ctrl.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_p.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/arrow.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_alt.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_ctrl.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_l.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/arrow.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_alt.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_ctrl.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_m.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/arrow.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_alt.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_ctrl.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_i.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/arrow.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_alt.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_ctrl.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_n.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/arrow.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_alt.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_ctrl.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_b.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/arrow.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_alt.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_ctrl.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_f.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/arrow.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_alt.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_ctrl.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_t.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/arrow.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_alt.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_ctrl.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_g.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/arrow.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_alt.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_ctrl.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_k.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/arrow.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_shift.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_alt.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_ctrl.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_a.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/arrow.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_shift.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_alt.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_ctrl.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_r.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/arrow.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_shift.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_alt.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_ctrl.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_c.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/arrow.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_shift.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_alt.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_ctrl.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_n.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/arrow.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_shift.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_alt.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_ctrl.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_h.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/arrow.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_alt.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_ctrl.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_o.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/arrow.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_alt.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_ctrl.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_e.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/arrow.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_alt.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_ctrl.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_d.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/arrow.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_alt.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_ctrl.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_s.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/arrow.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_alt.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_ctrl.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_r.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/arrow.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_alt.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_ctrl.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_h.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/arrow.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_alt.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_ctrl.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/key_o.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/arrow.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/dot_index.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/dot_index.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/dot_index.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/dot_index.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/dot_index.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/dot_index.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/dot_index.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/dot_index.png
ImageCache: Can't load bitmap! /boot/home/HaikuArchives/BePodder/release/icons/dot_index.png
BePodder: /home/builder/builds/haiku/src/system/libroot/posix/malloc/superblock.h:273:int BPrivate::superblock::isValid(): _numAvailable <= _numBlocks
Kill Thread
~/HaikuArchives/BePodder/release>

**Comment by Vidrep** [comment]
This is a bug only on 64 bit

**Comment by janus2** [comment]
I would like to change the help into something like the PecoRename documentation...
This will solve this and #65.

**Comment by Vidrep** [comment]
Humdinger is the expert in these matters...

**Comment by scottmc** [comment]
Marking this as a current BUG, but also an ENHANCEMENT and task.  Task would be to update the help system, which would in the process fix this bug.

**Comment by scottmc** [comment]
see #65
