### ISSUE TITLE
Build breakage on 64 bit with new toolbar

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/BePodder#64]
objects.x86_64-cc5-release/IABPChannel.o: In function `IABPChannelAddRequest::IABPChannelAddRequest(MainController*, MainWindow*)':
IABPChannel.cpp:(.text+0xac2): undefined reference to `ResourceVectorToBitmap(char const*, float)'
objects.x86_64-cc5-release/IABPChannel.o: In function `IABPChannelRemove::IABPChannelRemove(MainController*, MainWindow*)':
IABPChannel.cpp:(.text+0xc02): undefined reference to `ResourceVectorToBitmap(char const*, float)'
objects.x86_64-cc5-release/IABPChannel.o: In function `IABPChannelCheck::IABPChannelCheck(MainController*, MainWindow*)':
IABPChannel.cpp:(.text+0xd32): undefined reference to `ResourceVectorToBitmap(char const*, float)'
objects.x86_64-cc5-release/IABPChannel.o: In function `IABPChannelWWW::IABPChannelWWW(MainController*, MainWindow*)':
IABPChannel.cpp:(.text+0xe72): undefined reference to `ResourceVectorToBitmap(char const*, float)'
objects.x86_64-cc5-release/IABPItem.o: In function `IABPItemRemove::IABPItemRemove(MainController*, MainWindow*)':
IABPItem.cpp:(.text+0x572): undefined reference to `ResourceVectorToBitmap(char const*, float)'
objects.x86_64-cc5-release/IABPItem.o:IABPItem.cpp:(.text+0x58a): more undefined references to `ResourceVectorToBitmap(char const*, float)' follow
collect2: error: ld returned 1 exit status
/boot/system/develop/etc/makefile-engine:246: recipe for target 'objects.x86_64-cc5-release/BePodder' failed
make: *** [objects.x86_64-cc5-release/BePodder] Error 1

**Comment by diversys** [comment]
Tried ```make clean``` first?

**Comment by Vidrep** [comment]
Always. However, what I'll do now, is a git clone of the master just to be sure.

**Comment by Vidrep** [comment]
That did the trick.
