### ISSUE TITLE
Help menu needs rewrite

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/BePodder#65]
Current help menu refers to non-existent menu items, and is still showing old icon set.

**Comment by janus2** [comment]
@Vidrep the guide is good enough or do you think it needs a rewrite?

**Comment by Vidrep** [comment]
The Readme.html is the guide now, no? If that's the case, then yes, it's done and ready to go.

**Comment by janus2** [comment]
If someone wants improve the documentation please:
- modify the `doc/ReadMe.html` 
- create a PR.
