### ISSUE TITLE
Start with a large list of subscription is slow

### ISSUE THREAD

**Issue by diversys** [HaikuArchives/BePodder#73]
It shows parsing archive modal window for about 20 seconds. Intstead, it should do this in the background without blocking user unput.

**Comment by janus2** [comment]
How many subscriptions do you have?
Can you try my branch experimentalStart? It should be much faster...

**Comment by diversys** [comment]
A few hundreds subscriptions. experimentalStart starts in just 2 seconds! Would be nice to eliminate this "parsing archive" modal window completely. Thanks!
