### ISSUE TITLE
BePodder 1.5.0 shows a flash screen on startup

### ISSUE THREAD

**Issue by Begasus** [HaikuArchives/BePodder#81]
When launching the latest version I see a flash from a window that immediatly disapears ...

**Comment by Begasus** [comment]
New PR for the 1.5.0

**Comment by janus2** [comment]
Have you some feeds? I think the window you see is the "Parsing archive..."

Your machine is too fast...

![parsing archive](https://user-images.githubusercontent.com/10423645/46200786-d7136400-c312-11e8-9628-a47982c2effa.png)

**Comment by Begasus** [comment]
Ah, it's probably because no feeds are in yet, maybe a check for this could be included if no feeds are in there? (I'm guessing that on a first start it will happen to anyone who is trying it out for the first time) :)

**Comment by janus2** [comment]
As suggested by @diversys the optimal solution could be remove the window in any case. But at the moment the architecture of the application make this operation not practicable. We'll see in a future version.

**Comment by Begasus** [comment]
This could be closed then :)
