### ISSUE TITLE
No minimum window size

### ISSUE THREAD

**Issue by bach5000** [HaikuArchives/BePodder#96]
There are no restrictions on window sizing.
You don't want users to make the windows too small, or you end up having something like this :(
![screenshot1](https://user-images.githubusercontent.com/17076625/48044713-edeb7880-e152-11e8-8872-638a53022917.png)

**Comment by R4H33M** [comment]
Would using `BWindow::SetSizeLimits()` be adequate here?

**Comment by bach5000** [comment]
@R4H33M It doesn't hurt to try.

**Comment by waddlesplash** [comment]
What about AUTO_UPDATE_SIZE_LIMITS?
