### ISSUE TITLE
Auto resize title column

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/BePodder#99]
Often times the episode title is longer than the allowable width of the title column, and the title is truncated. There is plenty of room to allow for more characters. Auto-resizing the column to the longest title in the list would be ideal.

**Comment by janus2** [comment]
There is a system wide solution to this... Just double click over the separator line between the title and the next column.

![bestfits](https://user-images.githubusercontent.com/10423645/51783946-0eb7de80-2142-11e9-8cc4-e0aa955254ea.png)


> There is plenty of room to allow for more characters. 

This depends on the resolution of your screen and how many attributes you have, with low resolutions there isn't.
